### ISSUE TITLE
Issue #8

### ISSUE THREAD

**Issue by rr-** [win-iconv/win-iconv#25]
https://github.com/win-iconv/win-iconv/commit/045c6fee3fd911191b93601615e08c3a55425fab

This broke #8.

The author claims to add `const` "as it should be". Well, the standard says otherwise. Even `glibc` people are [pretty serious about keeping it non-`const`]( https://sourceware.org/bugzilla/show_bug.cgi?id=2962 ), quoting:

>**Ulrich Drepper** 2006-08-14 16:30:51 UTC
>What are you talking about?  That patch is completely, utterly wrong.  The
current code and the manual is correct, there is no problem.  The current spec
has already been revised with an interpretation request and the first draft of
the upcoming spec is fixed.  There is no const.  Period.  Your patch makes the
glibc of whatever moron is using it non-compliant.

At very least, please offer us a `#define` we can set to make the header export non-`const` version.

**Comment by ynkdir** [comment]
I added WINICONV_CONST macro in iconv.h.
Its defautl value is ICONV_CONST or const for now.

**Comment by rr-** [comment]
Thanks!
