### ISSUE TITLE
Document GLIB_COMPILATION macro

### ISSUE THREAD

**Issue by nalimilan** [win-iconv/win-iconv#27]
I discovered the `GLIB_COMPILATION` macro when reading the code, and I found it quite interesting. Would it be possible to add a word about it in the README? Mentioning whether it increases compliance with Unicode would be good.

It could also be given a more general name, but that's a detail.

**Comment by ynkdir** [comment]
I have forgotten much about it.  I think it may be nice to keep it as is without documentation.

**Comment by nalimilan** [comment]
Actually, I thought enabling it made `UTF-16` big-endian when endianness isn't specified, but that's actually the contrary. This is more consistent with glibc's iconv, but not with libiconv nor with RFC2781, so that's not very interesting.
